{"name": "test_04", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <testcase.test_demo2.TestCase object at 0x00000264CEBEA4D0>\n\n    def test_04(self):\n        print(\"---用例4执行---\")\n>       assert False\nE       assert False\n\ntestcase\\test_demo2.py:38: AssertionError"}, "attachments": [{"name": "log", "source": "ca855d1f-e25b-4e69-b790-3b2734893b04-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "2fc275ad-ead8-497d-b2d3-562dd41e0298-attachment.txt", "type": "text/plain"}], "start": 1753974846140, "stop": 1753974846140, "uuid": "dab8827a-4977-414c-8986-ba4240bb82ed", "historyId": "02490a258f3e4624d2a5c9b5a01c2c00", "testCaseId": "02490a258f3e4624d2a5c9b5a01c2c00", "fullName": "testcase.test_demo2.TestCase#test_04", "labels": [{"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_demo2"}, {"name": "subSuite", "value": "TestCase"}, {"name": "host", "value": "BF-202006262120"}, {"name": "thread", "value": "7116-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_demo2"}]}